services:
    orynider.translator.admin.controller:
        class: orynider\translator\controller\translator
        arguments:
            - '@cache.driver'
            - '@config'
            - '@service_container'
            - '@controller.helper'
            - '@dbal.conn'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'			
            - '%core.root_path%'
            - '%core.php_ext%'
    orynider.translator.core:
        class: orynider\translator\core\translator
        arguments:
            - '@cache.driver'
            - '@config'
            - '@service_container'
            - '@controller.helper'
            - '@dbal.conn'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'			
            - '%core.root_path%'
            - '%core.php_ext%'
    orynider.translator.googletranslater:
        class: orynider\translator\google_translater\google_translater
        arguments:	   
            - '@language'	   
            - '@request'	   
    orynider.translator.listener:
        class: orynider\translator\event\listener
        arguments:
            - '@template'
            - '@config'
        tags:
            - { name: event.listener }
